[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, x-whop-key, x-company-id, x-kit-key, x-sd-key, x-twitter-token, x-ig-token, x-ig-account-id, x-code-verifier"
